# Generated by Django 2.2.11 on 2020-03-11 08:08

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Host',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True, verbose_name='主机名')),
                ('ip', models.GenericIPAddressField(unique=True, verbose_name='IP 地址')),
                ('version', models.CharField(max_length=200, verbose_name='版本')),
                ('cpu', models.IntegerField(default=4, verbose_name='CPU 核数')),
                ('memory', models.CharField(default='8G', max_length=10, verbose_name='内存大小')),
                ('disk', models.CharField(default='80G', max_length=10, verbose_name='硬盘大小')),
                ('position', models.CharField(max_length=200, verbose_name='位置')),
                ('hostuser', models.CharField(default='root', max_length=200, verbose_name='系统管理员')),
                ('password', models.CharField(max_length=200, verbose_name='密码')),
                ('type', models.CharField(max_length=200, verbose_name='类别')),
                ('env', models.CharField(default='test', max_length=200, verbose_name='环境')),
                ('deleted', models.BooleanField(default='false', verbose_name='是否已删除')),
                ('created', models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间')),
            ],
        ),
    ]
