# Generated by Django 2.2.11 on 2020-03-11 08:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='host',
            old_name='hostuser',
            new_name='admin',
        ),
    ]
