# Generated by Django 2.2.11 on 2020-05-12 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20200512_1644'),
    ]

    operations = [
        migrations.AlterField(
            model_name='host',
            name='ip',
            field=models.GenericIPAddressField(verbose_name='IP 地址'),
        ),
        migrations.AlterUniqueTogether(
            name='host',
            unique_together={('ip', 'type')},
        ),
    ]
