# Generated by Django 2.2.11 on 2020-05-12 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20200512_1859'),
    ]

    operations = [
        migrations.AlterField(
            model_name='host',
            name='name',
            field=models.CharField(max_length=200, verbose_name='主机名'),
        ),
        migrations.AlterUniqueTogether(
            name='host',
            unique_together={('ip', 'type', 'name')},
        ),
    ]
