# Generated by Django 2.2.11 on 2020-08-10 02:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20200512_1859'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='env',
            name='name',
        ),
        migrations.AddField(
            model_name='env',
            name='name_cn',
            field=models.CharField(default='sit', max_length=200, unique=True, verbose_name='中文名'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='env',
            name='name_en',
            field=models.CharField(default='pro', max_length=200, unique=True, verbose_name='英文名'),
            preserve_default=False,
        ),
    ]
