# Generated by Django 2.2.11 on 2020-08-11 01:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20200810_1006'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='env',
            field=models.ManyToManyField(to='app.Env'),
        ),
    ]
