# Generated by Django 2.2.11 on 2020-08-11 03:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_auto_20200811_1130'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectjar',
            name='env',
            field=models.CharField(default='1', max_length=200, verbose_name='环境'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='projectjar',
            name='host',
            field=models.ManyToManyField(to='app.Host'),
        ),
        migrations.AddField(
            model_name='projectjar',
            name='port',
            field=models.CharField(default='1', max_length=200, verbose_name='端口号'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='projectjar',
            name='project',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.PROTECT, to='app.Project'),
            preserve_default=False,
        ),
    ]
