# Generated by Django 2.2.11 on 2020-08-11 03:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_auto_20200811_1131'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projectjar',
            name='host',
        ),
    ]
