# Generated by Django 2.2.11 on 2020-08-11 03:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_remove_projectjar_host'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectjar',
            name='host',
            field=models.ManyToManyField(to='app.Host'),
        ),
    ]
