# Generated by Django 2.2.11 on 2020-08-13 06:59

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_projectjar_created'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectWar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='名称')),
                ('dir', models.CharField(max_length=200, verbose_name='路径')),
                ('port', models.CharField(max_length=200, verbose_name='端口号')),
                ('env', models.CharField(max_length=200, verbose_name='环境')),
                ('created', models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间')),
                ('host', models.ManyToManyField(to='app.Host')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app.Project')),
            ],
        ),
    ]
