# Generated by Django 2.2.11 on 2020-08-13 07:22

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_projectwar'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectRedis',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('addr', models.CharField(max_length=200, verbose_name='地址')),
                ('port', models.CharField(max_length=200, verbose_name='端口号')),
                ('dir', models.CharField(blank=True, max_length=200, verbose_name='路径')),
                ('cluster', models.CharField(blank=True, max_length=200, verbose_name='集群名')),
                ('password', models.CharField(max_length=200, verbose_name='密码')),
                ('env', models.CharField(max_length=200, verbose_name='环境')),
                ('created', models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app.Project')),
            ],
        ),
    ]
