# Generated by Django 2.2.11 on 2020-08-17 02:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_projectjar_method'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectredis',
            name='method',
            field=models.CharField(default='normal', max_length=200, verbose_name='部署方式'),
        ),
    ]
