# Generated by Django 2.2.11 on 2020-08-17 04:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0018_projectphp'),
    ]

    operations = [
        migrations.RenameField(
            model_name='projectmysqldb',
            old_name='host',
            new_name='addr',
        ),
        migrations.AddField(
            model_name='projectmysqldb',
            name='name',
            field=models.CharField(default='db', max_length=200, verbose_name='数据库名'),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='projectmysqldb',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='projectmysqldb',
            name='mysqldb',
        ),
    ]
