# Generated by Django 2.2.11 on 2020-08-17 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0021_auto_20200817_1335'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectmysqldb',
            name='addr',
            field=models.CharField(max_length=200, verbose_name='地址'),
        ),
        migrations.AlterField(
            model_name='projectmysqldb',
            name='name',
            field=models.CharField(max_length=200, verbose_name='数据库名'),
        ),
    ]
