# Generated by Django 2.2.11 on 2020-08-17 05:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0022_auto_20200817_1336'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectmysqldb',
            name='env',
            field=models.CharField(max_length=200, verbose_name='环境'),
        ),
        migrations.AlterField(
            model_name='projectmysqldb',
            name='password',
            field=models.CharField(max_length=200, verbose_name='密码'),
        ),
        migrations.AlterField(
            model_name='projectmysqldb',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app.Project'),
        ),
        migrations.AlterField(
            model_name='projectmysqldb',
            name='role',
            field=models.CharField(max_length=200, verbose_name='角色'),
        ),
        migrations.AlterField(
            model_name='projectmysqldb',
            name='username',
            field=models.CharField(max_length=200, verbose_name='用户名'),
        ),
    ]
