# Generated by Django 2.2.11 on 2020-08-17 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0023_auto_20200817_1337'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectmysqldb',
            name='origin',
            field=models.CharField(default='自建', max_length=200, verbose_name='来源'),
        ),
    ]
