# Generated by Django 2.2.11 on 2020-08-18 03:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0024_projectmysqldb_origin'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectredis',
            name='origin',
            field=models.CharField(default='自建', max_length=200, verbose_name='来源'),
        ),
    ]
