# Generated by Django 2.2.11 on 2020-08-18 03:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0026_projectrabbitmq'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projectrabbitmq',
            name='role',
        ),
    ]
