# Generated by Django 2.2.11 on 2020-08-18 05:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0028_projectactivemq'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='software',
            name='type',
        ),
    ]
