# Generated by Django 2.2.11 on 2020-08-18 06:30

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0029_remove_software_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectZookeeper',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('addr', models.CharField(max_length=200, verbose_name='地址')),
                ('port', models.CharField(blank=True, max_length=200, verbose_name='端口号')),
                ('dir', models.CharField(blank=True, max_length=200, verbose_name='路径')),
                ('env', models.CharField(max_length=200, verbose_name='环境')),
                ('method', models.CharField(default='normal', max_length=200, verbose_name='部署方式')),
                ('origin', models.CharField(default='自建', max_length=200, verbose_name='来源')),
                ('created', models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app.Project')),
            ],
        ),
        migrations.CreateModel(
            name='ProjectKafka',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('addr', models.CharField(max_length=200, verbose_name='地址')),
                ('port', models.CharField(blank=True, max_length=200, verbose_name='端口号')),
                ('dir', models.CharField(blank=True, max_length=200, verbose_name='路径')),
                ('env', models.CharField(max_length=200, verbose_name='环境')),
                ('method', models.CharField(default='normal', max_length=200, verbose_name='部署方式')),
                ('origin', models.CharField(default='自建', max_length=200, verbose_name='来源')),
                ('created', models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app.Project')),
            ],
        ),
    ]
