# Generated by Django 2.2.11 on 2020-08-19 02:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0031_projectsqlserver'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectweb',
            name='dir',
            field=models.CharField(blank=True, max_length=200, verbose_name='路径'),
        ),
        migrations.AddField(
            model_name='projectweb',
            name='password',
            field=models.CharField(blank=True, max_length=200, verbose_name='密码'),
        ),
        migrations.AddField(
            model_name='projectweb',
            name='username',
            field=models.CharField(blank=True, max_length=200, verbose_name='用户名'),
        ),
    ]
