# Generated by Django 2.2.11 on 2020-08-19 02:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0032_auto_20200819_1006'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mysqldb',
            name='project',
        ),
        migrations.AlterUniqueTogether(
            name='projectgeneralsoftware',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='projectgeneralsoftware',
            name='host',
        ),
        migrations.RemoveField(
            model_name='projectgeneralsoftware',
            name='project',
        ),
        migrations.AlterUniqueTogether(
            name='projecttomcat',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='projecttomcat',
            name='host',
        ),
        migrations.DeleteModel(
            name='JavaPackage',
        ),
        migrations.DeleteModel(
            name='MySQLDB',
        ),
        migrations.DeleteModel(
            name='ProjectGeneralSoftware',
        ),
        migrations.DeleteModel(
            name='ProjectTomcat',
        ),
    ]
