# Generated by Django 2.2.11 on 2020-08-19 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0034_projectpython'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='username',
            field=models.CharField(max_length=200, verbose_name='用户名'),
        ),
    ]
