# Generated by Django 2.2.11 on 2020-08-20 03:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0035_auto_20200819_1628'),
    ]

    operations = [
        migrations.AddField(
            model_name='host',
            name='manage_port',
            field=models.IntegerField(default=22, verbose_name='管理端口号'),
        ),
        migrations.AddField(
            model_name='host',
            name='outside_ip',
            field=models.GenericIPAddressField(default='0.0.0.0', verbose_name='外网 IP'),
        ),
        migrations.AlterField(
            model_name='host',
            name='ip',
            field=models.GenericIPAddressField(verbose_name='内网 IP'),
        ),
    ]
