# Generated by Django 2.2.11 on 2020-08-20 03:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0036_auto_20200820_1145'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='remark',
            field=models.CharField(blank=True, max_length=255, verbose_name='备注'),
        ),
    ]
