# Generated by Django 2.2.11 on 2020-08-20 10:18

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0037_account_remark'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivemqInstance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inside_addr', models.CharField(max_length=200, verbose_name='内网地址')),
                ('outside_addr', models.CharField(blank=True, max_length=200, verbose_name='外网地址')),
                ('dir', models.CharField(blank=True, max_length=200, verbose_name='路径')),
                ('version', models.CharField(max_length=200, verbose_name='版本号')),
                ('method', models.CharField(default='normal', max_length=200, verbose_name='部署方式')),
                ('origin', models.CharField(default='自建', max_length=200, verbose_name='来源')),
                ('created', models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间')),
            ],
        ),
        migrations.CreateModel(
            name='MySQLInstance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inside_addr', models.CharField(max_length=200, verbose_name='内网地址')),
                ('outside_addr', models.CharField(blank=True, max_length=200, verbose_name='外网地址')),
                ('role', models.CharField(max_length=200, verbose_name='角色')),
                ('data_dir', models.CharField(blank=True, max_length=200, verbose_name='数据库路径')),
                ('version', models.CharField(max_length=200, verbose_name='版本号')),
                ('manager', models.CharField(max_length=200, verbose_name='管理员')),
                ('password', models.CharField(max_length=200, verbose_name='密码')),
                ('method', models.CharField(default='normal', max_length=200, verbose_name='部署方式')),
                ('origin', models.CharField(default='自建', max_length=200, verbose_name='来源')),
                ('created', models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间')),
            ],
        ),
        migrations.CreateModel(
            name='RabbitmqInstance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inside_addr', models.CharField(max_length=200, verbose_name='内网地址')),
                ('outside_addr', models.CharField(blank=True, max_length=200, verbose_name='外网地址')),
                ('dir', models.CharField(blank=True, max_length=200, verbose_name='数据库路径')),
                ('version', models.CharField(max_length=200, verbose_name='版本号')),
                ('method', models.CharField(default='normal', max_length=200, verbose_name='部署方式')),
                ('origin', models.CharField(default='自建', max_length=200, verbose_name='来源')),
                ('created', models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间')),
            ],
        ),
        migrations.CreateModel(
            name='RedisInstance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inside_addr', models.CharField(max_length=200, verbose_name='内网地址')),
                ('outside_addr', models.CharField(blank=True, max_length=200, verbose_name='外网地址')),
                ('dir', models.CharField(blank=True, max_length=200, verbose_name='路径')),
                ('version', models.CharField(max_length=200, verbose_name='版本号')),
                ('password', models.CharField(max_length=200, verbose_name='密码')),
                ('method', models.CharField(default='normal', max_length=200, verbose_name='部署方式')),
                ('origin', models.CharField(default='自建', max_length=200, verbose_name='来源')),
                ('created', models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间')),
            ],
        ),
        migrations.CreateModel(
            name='ZookeeperInstance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inside_addr', models.CharField(max_length=200, verbose_name='内网地址')),
                ('outside_addr', models.CharField(blank=True, max_length=200, verbose_name='外网地址')),
                ('dir', models.CharField(blank=True, max_length=200, verbose_name='路径')),
                ('version', models.CharField(max_length=200, verbose_name='版本号')),
                ('method', models.CharField(default='normal', max_length=200, verbose_name='部署方式')),
                ('origin', models.CharField(default='自建', max_length=200, verbose_name='来源')),
                ('created', models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间')),
            ],
        ),
    ]
