# Generated by Django 2.2.11 on 2020-08-21 03:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0038_activemqinstance_mysqlinstance_rabbitmqinstance_redisinstance_zookeeperinstance'),
    ]

    operations = [
        migrations.AddField(
            model_name='mysqlinstance',
            name='cluster',
            field=models.CharField(blank=True, max_length=200, verbose_name='集群'),
        ),
    ]
