# Generated by Django 2.2.11 on 2020-08-21 03:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0039_mysqlinstance_cluster'),
    ]

    operations = [
        migrations.AddField(
            model_name='activemqinstance',
            name='cluster',
            field=models.CharField(blank=True, max_length=200, verbose_name='集群'),
        ),
        migrations.AddField(
            model_name='rabbitmqinstance',
            name='cluster',
            field=models.CharField(blank=True, max_length=200, verbose_name='集群'),
        ),
        migrations.AddField(
            model_name='redisinstance',
            name='cluster',
            field=models.CharField(blank=True, max_length=200, verbose_name='集群'),
        ),
        migrations.AddField(
            model_name='zookeeperinstance',
            name='cluster',
            field=models.CharField(blank=True, max_length=200, verbose_name='集群'),
        ),
    ]
