# Generated by Django 2.2.11 on 2020-08-21 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0040_auto_20200821_1114'),
    ]

    operations = [
        migrations.AddField(
            model_name='activemqinstance',
            name='manager',
            field=models.CharField(default='admin', max_length=200, verbose_name='管理员'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='activemqinstance',
            name='password',
            field=models.CharField(default='123', max_length=200, verbose_name='密码'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='rabbitmqinstance',
            name='manager',
            field=models.CharField(default='aaaa', max_length=200, verbose_name='管理员'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='rabbitmqinstance',
            name='password',
            field=models.CharField(default='aaa', max_length=200, verbose_name='密码'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='rabbitmqinstance',
            name='dir',
            field=models.CharField(blank=True, max_length=200, verbose_name='路径'),
        ),
    ]
