# Generated by Django 2.2.11 on 2020-08-21 07:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0042_projectmysqldb_instance'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projectmysqldb',
            name='addr',
        ),
        migrations.RemoveField(
            model_name='projectmysqldb',
            name='dir',
        ),
        migrations.RemoveField(
            model_name='projectmysqldb',
            name='method',
        ),
        migrations.RemoveField(
            model_name='projectmysqldb',
            name='origin',
        ),
        migrations.RemoveField(
            model_name='projectmysqldb',
            name='port',
        ),
        migrations.RemoveField(
            model_name='projectmysqldb',
            name='role',
        ),
    ]
