# Generated by Django 2.2.11 on 2020-08-21 08:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0043_auto_20200821_1519'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectactivemq',
            name='instance',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='app.ActivemqInstance'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='projectrabbitmq',
            name='instance',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='app.RabbitmqInstance'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='projectredis',
            name='instance',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='app.RedisInstance'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='projectzookeeper',
            name='instance',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='app.ZookeeperInstance'),
            preserve_default=False,
        ),
    ]
