# Generated by Django 2.2.11 on 2020-08-21 09:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0044_auto_20200821_1618'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projectredis',
            name='addr',
        ),
        migrations.RemoveField(
            model_name='projectredis',
            name='cluster',
        ),
        migrations.RemoveField(
            model_name='projectredis',
            name='dir',
        ),
        migrations.RemoveField(
            model_name='projectredis',
            name='method',
        ),
        migrations.RemoveField(
            model_name='projectredis',
            name='origin',
        ),
        migrations.RemoveField(
            model_name='projectredis',
            name='password',
        ),
        migrations.RemoveField(
            model_name='projectredis',
            name='port',
        ),
    ]
