# Generated by Django 2.2.11 on 2020-08-21 09:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0045_auto_20200821_1738'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projectactivemq',
            name='addr',
        ),
        migrations.RemoveField(
            model_name='projectactivemq',
            name='dir',
        ),
        migrations.RemoveField(
            model_name='projectactivemq',
            name='method',
        ),
        migrations.RemoveField(
            model_name='projectactivemq',
            name='origin',
        ),
        migrations.RemoveField(
            model_name='projectactivemq',
            name='password',
        ),
        migrations.RemoveField(
            model_name='projectactivemq',
            name='port',
        ),
        migrations.RemoveField(
            model_name='projectactivemq',
            name='username',
        ),
        migrations.RemoveField(
            model_name='projectrabbitmq',
            name='addr',
        ),
        migrations.RemoveField(
            model_name='projectrabbitmq',
            name='dir',
        ),
        migrations.RemoveField(
            model_name='projectrabbitmq',
            name='method',
        ),
        migrations.RemoveField(
            model_name='projectrabbitmq',
            name='origin',
        ),
        migrations.RemoveField(
            model_name='projectrabbitmq',
            name='password',
        ),
        migrations.RemoveField(
            model_name='projectrabbitmq',
            name='port',
        ),
        migrations.RemoveField(
            model_name='projectrabbitmq',
            name='username',
        ),
        migrations.RemoveField(
            model_name='projectzookeeper',
            name='addr',
        ),
        migrations.RemoveField(
            model_name='projectzookeeper',
            name='dir',
        ),
        migrations.RemoveField(
            model_name='projectzookeeper',
            name='method',
        ),
        migrations.RemoveField(
            model_name='projectzookeeper',
            name='origin',
        ),
        migrations.RemoveField(
            model_name='projectzookeeper',
            name='port',
        ),
    ]
