# Generated by Django 2.2.11 on 2020-08-21 10:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0046_auto_20200821_1747'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectmysqldb',
            name='instance',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, to='app.MySQLInstance'),
        ),
    ]
