# Generated by Django 2.2.11 on 2020-08-25 02:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0049_auto_20200822_1204'),
    ]

    operations = [
        migrations.AddField(
            model_name='activemqinstance',
            name='web_addr',
            field=models.CharField(blank=True, max_length=200, verbose_name='Web 地址'),
        ),
        migrations.AddField(
            model_name='projectactivemq',
            name='password',
            field=models.CharField(blank=True, max_length=200, verbose_name='密码'),
        ),
        migrations.AddField(
            model_name='projectactivemq',
            name='username',
            field=models.CharField(blank=True, max_length=200, verbose_name='用户名'),
        ),
    ]
