# Generated by Django 2.2.11 on 2020-08-27 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0050_auto_20200825_1044'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='sort',
            field=models.CharField(default='other', max_length=200, verbose_name='类别'),
        ),
    ]
