# Generated by Django 2.2.11 on 2020-09-01 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0051_project_sort'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='env',
            options={'verbose_name': '环境', 'verbose_name_plural': '环境'},
        ),
        migrations.AlterModelOptions(
            name='project',
            options={'verbose_name': '项目', 'verbose_name_plural': '项目'},
        ),
        migrations.AlterModelOptions(
            name='software',
            options={'verbose_name': '软件语言', 'verbose_name_plural': '软件语言'},
        ),
        migrations.AddField(
            model_name='projectrabbitmq',
            name='password',
            field=models.CharField(blank=True, max_length=200, verbose_name='密码'),
        ),
        migrations.AddField(
            model_name='projectrabbitmq',
            name='username',
            field=models.CharField(blank=True, max_length=200, verbose_name='用户名'),
        ),
        migrations.AddField(
            model_name='rabbitmqinstance',
            name='web_addr',
            field=models.CharField(blank=True, max_length=200, verbose_name='Web 地址'),
        ),
    ]
