# Generated by Django 2.2.11 on 2020-10-21 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0053_project_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='status',
            field=models.CharField(default='使用', max_length=200, verbose_name='状态'),
        ),
    ]
