# Generated by Django 2.2.11 on 2020-10-21 10:02

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0054_auto_20201021_1620'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectCodeaddr',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='名称')),
                ('type', models.CharField(max_length=200, verbose_name='类别')),
                ('addr', models.CharField(max_length=200, verbose_name='地址')),
                ('created', models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app.Project')),
            ],
        ),
    ]
