# Generated by Django 2.2.11 on 2020-11-25 03:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0056_auto_20201022_0913'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='account',
            options={'ordering': ['use']},
        ),
        migrations.AlterField(
            model_name='account',
            name='use',
            field=models.CharField(max_length=255, verbose_name='名称'),
        ),
        migrations.AlterField(
            model_name='account',
            name='username',
            field=models.CharField(max_length=200, unique=True, verbose_name='用户名'),
        ),
    ]
