# Generated by Django 2.2.11 on 2021-01-27 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0057_auto_20201125_1111'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='use',
            field=models.CharField(max_length=255, unique=True, verbose_name='名称'),
        ),
        migrations.AlterField(
            model_name='account',
            name='username',
            field=models.CharField(max_length=200, verbose_name='用户名'),
        ),
    ]
