# Generated by Django 2.2.11 on 2021-01-27 07:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0059_l1menu_l2menu'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='l1menu',
            options={'verbose_name': '一级菜单', 'verbose_name_plural': '一级菜单'},
        ),
        migrations.AlterModelOptions(
            name='l2menu',
            options={'verbose_name': '二级菜单', 'verbose_name_plural': '二级菜单'},
        ),
        migrations.AlterField(
            model_name='l2menu',
            name='component',
            field=models.CharField(default="() => import('@/views/')", max_length=255, verbose_name='部件'),
        ),
        migrations.AlterField(
            model_name='l2menu',
            name='parent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app.L1Menu', verbose_name='父菜单'),
        ),
        migrations.AlterField(
            model_name='l2menu',
            name='path',
            field=models.CharField(max_length=255, unique=True, verbose_name='URI'),
        ),
    ]
