# Generated by Django 2.2.11 on 2021-01-27 08:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0060_auto_20210127_1546'),
    ]

    operations = [
        migrations.AlterField(
            model_name='l2menu',
            name='parent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='children', to='app.L1Menu', verbose_name='父菜单'),
        ),
    ]
