# Generated by Django 2.2.11 on 2021-02-02 03:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0061_auto_20210127_1619'),
    ]

    operations = [
        migrations.AddField(
            model_name='l1menu',
            name='order',
            field=models.IntegerField(default=10, verbose_name='排序'),
        ),
        migrations.AlterField(
            model_name='l1menu',
            name='component',
            field=models.CharField(default='Layout', help_text='固定值，不能变动', max_length=255, verbose_name='部件'),
        ),
        migrations.AlterField(
            model_name='l1menu',
            name='path',
            field=models.CharField(help_text='需要 /，例如: /resource', max_length=255, unique=True, verbose_name='URI'),
        ),
        migrations.AlterField(
            model_name='l2menu',
            name='component',
            field=models.CharField(help_text='相对于 /views 的路径, 例如: /resource/host', max_length=255, verbose_name='部件'),
        ),
        migrations.AlterField(
            model_name='l2menu',
            name='path',
            field=models.CharField(help_text='不需要 /，例如: user', max_length=255, unique=True, verbose_name='URI'),
        ),
    ]
