# Generated by Django 2.2.11 on 2021-02-02 03:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0062_auto_20210202_1141'),
    ]

    operations = [
        migrations.AlterField(
            model_name='l1menu',
            name='redirect',
            field=models.CharField(help_text='访问一级菜单跳转到子节点 URI，例如: /host', max_length=255, verbose_name='定向'),
        ),
    ]
