# Generated by Django 2.2.11 on 2021-02-02 06:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0064_auto_20210202_1156'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='l2menu',
            options={'ordering': ['order'], 'verbose_name': '二级菜单', 'verbose_name_plural': '二级菜单'},
        ),
        migrations.RemoveField(
            model_name='l1menu',
            name='component',
        ),
    ]
