# Generated by Django 2.2.11 on 2021-02-02 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0067_l2menu_is_model'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='l2menu',
            name='name',
        ),
        migrations.AlterField(
            model_name='l2menu',
            name='is_model',
            field=models.BooleanField(default=True, verbose_name='是否对应模型'),
        ),
    ]
