# Generated by Django 2.2.11 on 2021-02-02 09:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0069_l2menu_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='l2menu',
            name='name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='contenttypes.ContentType'),
        ),
    ]
