# Generated by Django 2.2.11 on 2021-02-02 09:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0070_auto_20210202_1738'),
    ]

    operations = [
        migrations.AlterField(
            model_name='l2menu',
            name='name',
            field=models.ForeignKey(blank=True, limit_choices_to={'app_label': 'app'}, null=True, on_delete=django.db.models.deletion.PROTECT, to='contenttypes.ContentType', verbose_name='名称'),
        ),
    ]
