# Generated by Django 3.2 on 2021-04-26 02:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('app', '0071_auto_20210202_1749'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='project',
            options={'ordering': ['name'], 'verbose_name': '项目', 'verbose_name_plural': '项目'},
        ),
        migrations.AddField(
            model_name='projectredis',
            name='db',
            field=models.CharField(default=0, max_length=10, verbose_name='数据库'),
        ),
        migrations.AlterField(
            model_name='l2menu',
            name='name',
            field=models.ForeignKey(blank=True, help_text='绑定模型', limit_choices_to={'app_label': 'app'}, null=True, on_delete=django.db.models.deletion.PROTECT, to='contenttypes.contenttype', verbose_name='模型'),
        ),
    ]
